# AutoGrad: 파이토치에서 신경망모형(딥러닝 모형)의 파라미터(가중치)를 Back Propagation(역전파 알고리즘) 방법으로 갱신하는 방식 
# 하이퍼 파라미터: Batch Size(한 번의 학습에 이용되는 데이터의 개수), Input Size(입력층의 크기), Hidden Size(은닉층의 크기), Output Size(출력층의 크기) 

In [2]:
import torch

if torch.cuda.is_available():
    print("1")
    DEVICE = torch.device('cuda')
else :
    print("2")
    DEVICE = torch.device('cpu')

1


In [3]:
BATCH_SIZE = 64
INPUT_SIZE = 1000
HIDDEN_SIZE = 100
OUTPUT_SIZE = 10
print(BATCH_SIZE)
print(INPUT_SIZE)
print(HIDDEN_SIZE)
print(OUTPUT_SIZE)

64
1000
100
10


In [4]:
x=torch.randn(BATCH_SIZE,INPUT_SIZE,device=DEVICE,dtype=torch.float,requires_grad=False)
print(x)

tensor([[-0.3472, -0.2844,  1.3831,  ..., -0.7780, -0.7805, -0.7981],
        [-0.0439, -0.3154, -0.5891,  ...,  0.1596, -0.3977, -0.0730],
        [ 0.4698, -1.4643, -0.0206,  ...,  0.3084,  0.4743, -1.1922],
        ...,
        [-0.2716, -0.1357,  0.9786,  ..., -0.4945, -0.5342, -0.4858],
        [ 0.0783, -0.1756, -0.5569,  ...,  1.4327, -0.6628,  2.3921],
        [ 0.4144,  0.6558, -0.3255,  ..., -1.4797,  0.2802, -0.3615]],
       device='cuda:0')


In [5]:
y=torch.randn(BATCH_SIZE,OUTPUT_SIZE,device=DEVICE,dtype=torch.float,requires_grad=False)
print(y)

tensor([[-1.8530e+00,  9.5558e-01,  5.9204e-01,  2.5927e+00,  1.2323e+00,
          8.2790e-01, -7.3366e-01, -2.7680e-01,  1.5567e+00,  1.0067e+00],
        [ 6.9557e-01,  2.6945e-02, -5.1100e-01,  1.2435e+00,  1.3706e+00,
          9.6595e-01,  8.8959e-01, -2.9993e+00,  2.3642e+00, -8.9115e-01],
        [-6.6504e-01, -1.2196e+00, -2.9167e-01, -8.0918e-01, -1.8093e+00,
          4.1296e-01, -1.6075e-01,  1.1430e+00,  1.3035e+00,  1.5381e-01],
        [ 6.1037e-01,  1.0919e+00,  8.4245e-01, -2.1539e-01, -5.4343e-01,
          1.7155e+00,  1.8518e+00,  1.3941e+00, -7.8635e-01, -6.9299e-01],
        [ 4.5049e-01,  2.2289e+00, -8.8878e-01, -1.0892e+00, -1.7587e-01,
         -4.9869e-01,  8.2107e-01, -1.2232e+00,  6.3506e-01, -1.0197e+00],
        [ 6.8171e-01,  8.2940e-01, -7.3289e-01,  3.1708e-01,  6.5727e-01,
          9.2267e-01, -1.9855e-01,  3.5818e-01, -4.5277e-01, -5.5242e-01],
        [-4.7818e-01, -7.8012e-01,  7.5900e-01,  2.2500e-01, -4.7367e-01,
         -6.8220e-01,  1.5483e-0

In [6]:
w1 = torch.randn(INPUT_SIZE,HIDDEN_SIZE,device=DEVICE,dtype=torch.float,requires_grad=True)
print(w1)

tensor([[ 1.1558, -1.8770,  0.3727,  ...,  0.6006, -0.2452, -0.4781],
        [ 0.0435, -0.3206, -0.0515,  ..., -0.7969, -0.7503, -0.2175],
        [ 0.1623,  0.2895, -0.2019,  ..., -1.6586, -1.6151, -1.3054],
        ...,
        [ 0.8176, -0.1052,  1.8702,  ..., -1.1426, -0.9309,  0.3226],
        [ 1.0516,  0.5848,  0.3072,  ...,  0.1789, -0.3416, -1.3365],
        [ 1.0128, -0.2565, -0.7935,  ..., -0.1540, -1.5766, -0.2827]],
       device='cuda:0', requires_grad=True)


In [7]:
w2 = torch.randn(HIDDEN_SIZE,OUTPUT_SIZE,device=DEVICE,dtype=torch.float,requires_grad=True)
print(w2)

tensor([[ 0.2685, -0.0107, -1.5547,  0.7696,  0.5222,  1.3323,  0.5476, -1.0761,
         -0.9530, -1.2299],
        [-0.6992,  1.0908, -0.2788, -0.3280,  0.8391,  0.1935, -0.1990,  1.2434,
         -0.6037, -0.0550],
        [ 0.0538, -0.4143,  0.2095, -0.2588, -0.1758,  2.8261, -0.6577,  0.8684,
         -0.1048, -1.4729],
        [ 0.6510, -0.2509,  0.4118, -0.0186, -0.3641, -2.3178,  2.6740,  0.4355,
         -0.4119,  1.6004],
        [ 2.3180, -0.3865, -0.5004,  0.1511,  0.9597,  0.2906, -0.8922,  0.2010,
          0.7942,  0.7810],
        [ 0.4293, -0.1104,  0.0935,  0.9722, -0.0875, -0.0424, -0.2489,  0.2924,
         -0.9938, -0.0347],
        [ 0.6443, -0.4126,  1.6561, -2.0383,  0.6112, -0.4261,  0.5195, -1.5962,
          0.2516, -0.0397],
        [-0.3021,  0.0441, -1.0270,  1.4224,  0.7542,  0.9374,  2.4011,  0.3338,
          1.2661, -0.1054],
        [ 0.7471,  1.4349, -0.2650,  1.0907,  0.6699,  0.4069,  0.9249,  1.1141,
          0.8600, -0.6736],
        [ 1.0567,  

In [8]:
learning_rate=1e-6
for t in range(1,501):
    y_pred = x.mm(w1).clamp(min=0).mm(w2)
    
    loss =(y_pred-y).pow(2).sum()
    if t % 100 == 0:
        print(f"Iteration:{t} \t Loss: ", loss.item())
    loss.backward()
    
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        
        w1.grad.zero_()
        w2.grad.zero_() 

Iteration:100 	 Loss:  223.15829467773438
Iteration:200 	 Loss:  0.4275420904159546
Iteration:300 	 Loss:  0.001838726457208395
Iteration:400 	 Loss:  8.796722977422178e-05
Iteration:500 	 Loss:  2.34667859331239e-05


In [9]:
import torch

if torch.cuda.is_available():
    print("1")
    DEVICE = torch.device('cuda')
else :
    print("2")
    DEVICE = torch.device('cpu')

BATCH_SIZE = 64
INPUT_SIZE = 1000
HIDDEN_SIZE = 100
OUTPUT_SIZE = 10 

x=torch.randn(BATCH_SIZE,INPUT_SIZE,device=DEVICE,dtype=torch.float,requires_grad=False)
y=torch.randn(BATCH_SIZE,OUTPUT_SIZE,device=DEVICE,dtype=torch.float,requires_grad=False)
w1 = torch.randn(INPUT_SIZE,HIDDEN_SIZE,device=DEVICE,dtype=torch.float,requires_grad=True)
w2 = torch.randn(HIDDEN_SIZE,OUTPUT_SIZE,device=DEVICE,dtype=torch.float,requires_grad=True)

learning_rate=1e-6
for t in range(1,501):
    y_pred = x.mm(w1).clamp(min=0).mm(w2)
    
    loss =(y_pred-y).pow(2).sum()
    if t % 100 == 0:
        print(f"Iteration:{t} \t Loss: ", loss.item())
    loss.backward()
    
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        
        w1.grad.zero_()
        w2.grad.zero_()


1
Iteration:100 	 Loss:  1126.988037109375
Iteration:200 	 Loss:  18.63925552368164
Iteration:300 	 Loss:  0.5602846145629883
Iteration:400 	 Loss:  0.02398347482085228
Iteration:500 	 Loss:  0.0016595259075984359
