Word Embedding / One-Hot Encoding

In [2]:
S1 = '나는 책상 위에 사과를 먹었다'
S2 = '알고 보니 그 사과는 Jason 것이었다'
S3 = '그래서 Jason에게 사과를 했다'

token2idx={}
index=0

for sentence in [S1,S2,S3]:
    tokens =sentence.split()
    for token in tokens:
        if token2idx.get(token) == None:
            token2idx[token]=index
            index+=1
            
print(token2idx)

{'나는': 0, '책상': 1, '위에': 2, '사과를': 3, '먹었다': 4, '알고': 5, '보니': 6, '그': 7, '사과는': 8, 'Jason': 9, '것이었다': 10, '그래서': 11, 'Jason에게': 12, '했다': 13}


In [2]:
V = len(token2idx)

token2vec = [([0 if i != idx else 1 for i in range(V)], idx, token) for token, idx in token2idx.items()]

for x in token2vec:
    print("\t".join([str(y) for y in x]))

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]	0	나는
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]	1	책상
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]	2	위에
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]	3	사과를
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]	4	먹었다
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]	5	알고
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]	6	보니
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]	7	그
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]	8	사과는
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]	9	Jason
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]	10	것이었다
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]	11	그래서
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]	12	Jason에게
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]	13	했다


In [3]:
import numpy as np

for sentence in [S1,S2,S3]:
    onehot_s = []
    tokens = sentence.split()
    for token in tokens:
        if token2idx.get(token) != None:
            vector = np.zeros((1,V))
            vector[:,token2idx[token]] = 1
            onehot_s.append(vector)
        else: 
            print("UNK")
            
    print(f"{sentence}: ")
    print(np.concatenate(onehot_s, axis = 0))
    print("\n")

나는 책상 위에 사과를 먹었다: 
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


알고 보니 그 사과는 Jason 것이었다: 
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


그래서 Jason에게 사과를 했다: 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]




In [4]:
# Bag of Word 예시
sentence = ["그래서", "Jason에게", "사과를", "했다"]

# 단어 등장 횟수 세기
freq_dict = {}
for token in sentence:
    if token in freq_dict:
        freq_dict[token] += 1
    else:
        freq_dict[token] = 1

print(freq_dict)

{'그래서': 1, 'Jason에게': 1, '사과를': 1, '했다': 1}


In [5]:
paragraph = ["나는", "사과를", "먹었다", "그래서", "Jason에게", "사과를", "했다"]

freq_dict = {}
for token in paragraph:
    freq_dict[token] = freq_dict.get(token, 0) + 1

print(freq_dict)


{'나는': 1, '사과를': 2, '먹었다': 1, '그래서': 1, 'Jason에게': 1, '했다': 1}


Reading Data

In [3]:
from datasets import load_dataset
from transformers import AutoTokenizer

# 데이터 로드 (Hugging Face 라이브러리 사용)
raw_datasets = load_dataset("imdb")

# 토크나이저 준비 (BERT 기반 토크나이저가 현재 업계 표준임)
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

# 설정값 보관
fix_length = 500

# Data Length 확인
print(f"Train Data Length : {len(raw_datasets['train'])}")
print(f"Test Data Length : {len(raw_datasets['test'])}")

# Data Fields 확인 (Label과 Text 컬럼 확인)
print(raw_datasets['train'].column_names)

# Data Sample 확인
print('---- Data Sample ----')
print('Input : ')
print(raw_datasets['train'][1]['text'], '\n')
print('Label : ')
print(raw_datasets['train'][1]['label']) # 0: neg, 1: pos

/home/centa/miniconda3/envs/firstproject/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Train Data Length : 25000
Test Data Length : 25000
['text', 'label']
---- Data Sample ----
Input : 
"I Am Curious: Yellow" is a risible and pretentious steaming pile. It doesn't matter what one's political views are because this film can hardly be taken seriously on any level. As for the claim that frontal male nudity is an automatic NC-17, that isn't true. I've seen R-rated films with male nudity. Granted, they only offer some fleeting views, but where are the R-rated films with gaping vulvas and flapping labia? Nowhere, because they don't exist. The same goes for those crappy cable shows: schlongs swinging in the breeze but not a clitoris in sight. And those pretentious indie movies like The Brown Bunny, in which we're treated to the site of Vincent Gallo's throbbing johnson, but not a trace of pink visible on Chloe Sevigny. Before crying (or implying) "double-standard" in matters of nudity, the mentally obtuse should take into account one unavoidably obvious anatomical difference be

Pre-processing Data

In [4]:
# Transformers는 토크나이저 내부에서 소문자화, 특수문자 처리를 지원함
# fix_length=500과 패딩/커팅을 한 번에 처리하는 함수 정의
def tokenize_function(examples):
    return tokenizer(
        examples["text"], 
        padding="max_length", 
        truncation=True, 
        max_length=fix_length
    )

# 데이터셋 전체에 실시간 전처리 적용 (map 방식이 루프보다 압도적으로 빠름)
tokenized_datasets = raw_datasets.map(tokenize_function, batched=True)

# 전처리 후 결과 샘플 확인 (수치화된 ID 확인)
print('---- Preprocessed Data Sample (Input IDs) ----')
print(tokenized_datasets['train'][1]['input_ids'][:20]) # 처음 20개 토큰만 출력

Map: 100%|██████████| 50000/50000 [00:09<00:00, 5401.94 examples/s]

---- Preprocessed Data Sample (Input IDs) ----
[101, 1000, 1045, 2572, 8025, 1024, 3756, 1000, 2003, 1037, 15544, 19307, 1998, 3653, 6528, 20771, 19986, 8632, 1012, 2009]


Making Vocab & Setting Embedding

In [5]:
# 이미 토크나이저 안에 수만 개의 단어가 포함되어 있음
vocab_size = tokenizer.vocab_size
model_config = {'vocab_size': vocab_size, 'emb_dim': 768} # BERT 기본 차원

# Vocabulary Info 확인 (stoi 역할)
print(f'Vocab Size : {vocab_size}')
print('Vocab Examples : ')
# 10개만 추출해서 확인
for word, idx in list(tokenizer.get_vocab().items())[:10]:
    print('\t', word, idx)

print('---------------------------------')

# Label Info 확인 (IMDB는 0: neg, 1: pos로 고정됨)
label_names = raw_datasets['train'].features['label'].names
print(f'Label Size : {len(label_names)}')
print('Lable Examples : ')
for i, name in enumerate(label_names):
    print('\t', name, i)

Vocab Size : 30522
Vocab Examples : 
	 setup 16437
	 slade 18048
	 missile 7421
	 disks 23999
	 suffolk 12291
	 collin 22180
	 blinking 15997
	 patterned 25336
	 ˢ 1152
	 enthusiasts 20305
---------------------------------
Label Size : 2
Lable Examples : 
	 neg 0
	 pos 1


Spliting Validation Data & Making Data Iterator

In [7]:
import torch
from torch.utils.data import DataLoader

# 훈련 데이터를 8:2로 다시 분할
train_valid_split = tokenized_datasets["train"].train_test_split(test_size=0.2, seed=0)
train_ds = train_valid_split["train"]
valid_ds = train_valid_split["test"]
test_ds = tokenized_datasets["test"]

# PyTorch용 텐서 포맷으로 변경
train_ds.set_format(type='torch', columns=['input_ids', 'label'])
valid_ds.set_format(type='torch', columns=['input_ids', 'label'])
test_ds.set_format(type='torch', columns=['input_ids', 'label'])

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# DataLoader 생성 (기존 BucketIterator 역할)
train_loader = DataLoader(train_ds, batch_size=30, shuffle=True)
valid_loader = DataLoader(valid_ds, batch_size=30)
test_loader = DataLoader(test_ds, batch_size=30)

5. Check Batch Data

In [8]:
# 배치 데이터 하나 확인
batch = next(iter(train_loader))

# 텐서 형태 출력
print(f"Batch Size/Fix Length: {batch['input_ids'].shape}") # [30, 500]
print(f"Labels: {batch['label']}")

# 역변환 확인 (숫자 -> 문장)
# tokenizer.decode를 사용하면 패딩 등을 제외하고 깔끔하게 문장으로 복구함
decoded_sentence = tokenizer.decode(batch['input_ids'][0], skip_special_tokens=True)
print(f"Reverted Sentence: {decoded_sentence[:200]}...")

# 라벨 정보 확인
print(f"Label Mapping: 1 is 'pos', 0 is 'neg' -> Result: {batch['label'][0]}")

Batch Size/Fix Length: torch.Size([30, 500])
Labels: tensor([1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
        1, 0, 1, 1, 0, 1])
Reverted Sentence: this is one of my favorite movies of all time. i loved rain man with dustin hoffman and tom cruise. this movie is in some ways similar, but makes rain man seem artificial, shallow, unemotional, and tr...
Label Mapping: 1 is 'pos', 0 is 'neg' -> Result: 1


TRANSFORMER - DATASET  라이브러리 기반 코드 최신화 및 사전 코드 가동 체크 & 결과 확인  

In [1]:
import torch
from datasets import load_dataset
from transformers import AutoTokenizer

# 데이터 로드
dataset = load_dataset("imdb")

# 전처리 (기존 코드의 fix_length=500과 동일)
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True, max_length=500)

tokenized_datasets = dataset.map(tokenize_function, batched=True)
tokenized_datasets.set_format(type='torch', columns=['input_ids', 'label'])

print("복구된 2.8.0 환경에서 데이터 로드 완료.")

/home/centa/miniconda3/envs/firstproject/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Map: 100%|██████████| 50000/50000 [00:10<00:00, 4757.36 examples/s]

복구된 2.8.0 환경에서 데이터 로드 완료.


In [4]:
# 'appropriate update'라는 단어가 들어간 리뷰 검색
search_term = "appropriate update"
results = [d for d in dataset['train'] if search_term in d['text'].lower()]

print(f"\n검색 결과: {len(results)}개의 리뷰를 찾았습니다.")

if results:
    print("-" * 50)
    print("첫 번째 검색 결과 내용:")
    print(results[0]['text'][:500] + "...") # 500자만 출력


검색 결과: 1개의 리뷰를 찾았습니다.
--------------------------------------------------
첫 번째 검색 결과 내용:
This is definitely an appropriate update for the original, except that "party on the left is now party on the right." Like the original, this movie rails against a federal government which oversteps its bounds with regards to personal liberty. It is a warning of how tenuous our political liberties are in an era of an over-zealous, and over-powerful federal government. Kowalski serves as a metaphor for Waco and Ruby Ridge, where the US government, with the cooperation of the mainstream media, thr...


In [5]:
# 훈련 데이터셋의 첫 번째 샘플 꺼내기
sample = tokenized_datasets['train'][0]

print("--- 데이터 샘플 확인 ---")
print(f"라벨 (0:부정, 1:긍정): {sample['label']}")
print(f"숫자로 변환된 텍스트(ID) 일부: {sample['input_ids'][:10]}") 
print(f"전체 길이: {len(sample['input_ids'])}") # 설정하신 500이 나와야 합니다.

--- 데이터 샘플 확인 ---
라벨 (0:부정, 1:긍정): 0
숫자로 변환된 텍스트(ID) 일부: tensor([  101,  1045, 12524,  1045,  2572,  8025,  1011,  3756,  2013,  2026])
전체 길이: 500
