Word Embedding / One-Hot Encoding

In [2]:
S1 = '나는 책상 위에 사과를 먹었다'
S2 = '알고 보니 그 사과는 Jason 것이었다'
S3 = '그래서 Jason에게 사과를 했다'

token2idx={}
index=0

for sentence in [S1,S2,S3]:
    tokens =sentence.split()
    for token in tokens:
        if token2idx.get(token) == None:
            token2idx[token]=index
            index+=1
            
print(token2idx)

{'나는': 0, '책상': 1, '위에': 2, '사과를': 3, '먹었다': 4, '알고': 5, '보니': 6, '그': 7, '사과는': 8, 'Jason': 9, '것이었다': 10, '그래서': 11, 'Jason에게': 12, '했다': 13}


In [2]:
V = len(token2idx)

token2vec = [([0 if i != idx else 1 for i in range(V)], idx, token) for token, idx in token2idx.items()]

for x in token2vec:
    print("\t".join([str(y) for y in x]))

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]	0	나는
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]	1	책상
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]	2	위에
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]	3	사과를
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]	4	먹었다
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]	5	알고
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]	6	보니
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]	7	그
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]	8	사과는
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]	9	Jason
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]	10	것이었다
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]	11	그래서
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]	12	Jason에게
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]	13	했다


In [3]:
import numpy as np

for sentence in [S1,S2,S3]:
    onehot_s = []
    tokens = sentence.split()
    for token in tokens:
        if token2idx.get(token) != None:
            vector = np.zeros((1,V))
            vector[:,token2idx[token]] = 1
            onehot_s.append(vector)
        else: 
            print("UNK")
            
    print(f"{sentence}: ")
    print(np.concatenate(onehot_s, axis = 0))
    print("\n")

나는 책상 위에 사과를 먹었다: 
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


알고 보니 그 사과는 Jason 것이었다: 
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


그래서 Jason에게 사과를 했다: 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]




In [4]:
# Bag of Word 예시
sentence = ["그래서", "Jason에게", "사과를", "했다"]

# 단어 등장 횟수 세기
freq_dict = {}
for token in sentence:
    if token in freq_dict:
        freq_dict[token] += 1
    else:
        freq_dict[token] = 1

print(freq_dict)

{'그래서': 1, 'Jason에게': 1, '사과를': 1, '했다': 1}


In [5]:
paragraph = ["나는", "사과를", "먹었다", "그래서", "Jason에게", "사과를", "했다"]

freq_dict = {}
for token in paragraph:
    freq_dict[token] = freq_dict.get(token, 0) + 1

print(freq_dict)


{'나는': 1, '사과를': 2, '먹었다': 1, '그래서': 1, 'Jason에게': 1, '했다': 1}


In [1]:
import torch
from datasets import load_dataset
from transformers import AutoTokenizer

# 데이터 로드
dataset = load_dataset("imdb")

# 전처리 (기존 코드의 fix_length=500과 동일)
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True, max_length=500)

tokenized_datasets = dataset.map(tokenize_function, batched=True)
tokenized_datasets.set_format(type='torch', columns=['input_ids', 'label'])

print("복구된 2.8.0 환경에서 데이터 로드 완료.")

/home/centa/miniconda3/envs/firstproject/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Map: 100%|██████████| 50000/50000 [00:10<00:00, 4757.36 examples/s]

복구된 2.8.0 환경에서 데이터 로드 완료.


In [4]:
# 'appropriate update'라는 단어가 들어간 리뷰 검색
search_term = "appropriate update"
results = [d for d in dataset['train'] if search_term in d['text'].lower()]

print(f"\n검색 결과: {len(results)}개의 리뷰를 찾았습니다.")

if results:
    print("-" * 50)
    print("첫 번째 검색 결과 내용:")
    print(results[0]['text'][:500] + "...") # 500자만 출력


검색 결과: 1개의 리뷰를 찾았습니다.
--------------------------------------------------
첫 번째 검색 결과 내용:
This is definitely an appropriate update for the original, except that "party on the left is now party on the right." Like the original, this movie rails against a federal government which oversteps its bounds with regards to personal liberty. It is a warning of how tenuous our political liberties are in an era of an over-zealous, and over-powerful federal government. Kowalski serves as a metaphor for Waco and Ruby Ridge, where the US government, with the cooperation of the mainstream media, thr...


In [5]:
# 훈련 데이터셋의 첫 번째 샘플 꺼내기
sample = tokenized_datasets['train'][0]

print("--- 데이터 샘플 확인 ---")
print(f"라벨 (0:부정, 1:긍정): {sample['label']}")
print(f"숫자로 변환된 텍스트(ID) 일부: {sample['input_ids'][:10]}") 
print(f"전체 길이: {len(sample['input_ids'])}") # 설정하신 500이 나와야 합니다.

--- 데이터 샘플 확인 ---
라벨 (0:부정, 1:긍정): 0
숫자로 변환된 텍스트(ID) 일부: tensor([  101,  1045, 12524,  1045,  2572,  8025,  1011,  3756,  2013,  2026])
전체 길이: 500
