# tensor 텐서
텐서(Tensor)란, '데이터를 표현하는 단위' 

In [150]:
import torch

scalar1= torch.tensor([1.])
print(scalar1)

tensor([1.])


In [151]:
scalar2= torch.tensor([3.])
print(scalar2)

tensor([3.])


In [152]:
add_scalar = scalar1 + scalar2
print(add_scalar)

tensor([4.])


In [153]:
sub_scalar = scalar1 - scalar2
print(sub_scalar)

tensor([-2.])


In [154]:
mul_scalar= scalar1 * scalar2
print(mul_scalar)

tensor([3.])


In [155]:
div_scalar = scalar1 / scalar2
print(div_scalar)

tensor([0.3333])


In [156]:
torch.add(scalar1,scalar2)

tensor([4.])

In [157]:
torch.sub(scalar1,scalar2)

tensor([-2.])

In [158]:
torch.mul(scalar1,scalar2)

tensor([3.])

In [159]:
torch.div(scalar1,scalar2)

tensor([0.3333])

# Vector : 벡터
하나의 값을 표현할 떄 2개 이상의 수치로 표현한 것

In [160]:
vector1 = torch.tensor([1.,2.,3.])
print(vector1)

tensor([1., 2., 3.])


In [161]:
vector2 = torch.tensor([4.,5.,6.])
print(vector2)

tensor([4., 5., 6.])


In [162]:
add_vector = vector1 + vector2
print(add_vector)

tensor([5., 7., 9.])


In [163]:
sub_vector = vector1 - vector2
print(sub_vector)

tensor([-3., -3., -3.])


In [164]:
mul_vector = vector1 * vector2
print(mul_vector)

tensor([ 4., 10., 18.])


In [165]:
div_vector = vector1 / vector2
print(div_vector)

tensor([0.2500, 0.4000, 0.5000])


In [166]:
torch.add(vector1,vector2)

tensor([5., 7., 9.])

In [167]:
torch.sub(vector1,vector2)

tensor([-3., -3., -3.])

In [168]:
torch.mul(vector1,vector2)

tensor([ 4., 10., 18.])

In [169]:
torch.div(vector1,vector2)

tensor([0.2500, 0.4000, 0.5000])

In [170]:
torch.dot(vector1,vector2)

tensor(32.)

# Matrix : 행렬
행렬은 2개 이상의 벡터 값을 통합해 구성된 값으로, 벡터 값 간 연산 속도를 빠르게 진행할 수 있는 선형 대수의 기본 단위

In [171]:
matrix1 = torch.tensor([[1., 2.],[3.,4.]])
print(matrix1)

tensor([[1., 2.],
        [3., 4.]])


In [172]:
matrix2 = torch.tensor([[5., 6.],[7.,8.]])
print(matrix2)

tensor([[5., 6.],
        [7., 8.]])


In [173]:
sum_matrix = matrix1 + matrix2
print(sum_matrix)

tensor([[ 6.,  8.],
        [10., 12.]])


In [174]:
sub_matrix = matrix1 - matrix2
print(sub_matrix)

tensor([[-4., -4.],
        [-4., -4.]])


In [175]:
mul_matrix = matrix1 * matrix2
print(mul_matrix)

tensor([[ 5., 12.],
        [21., 32.]])


In [176]:
div_matrix = matrix1 / matrix2
print(div_matrix)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [177]:
torch.add(matrix1,matrix2)

tensor([[ 6.,  8.],
        [10., 12.]])

In [178]:
torch.sub(matrix1,matrix2)

tensor([[-4., -4.],
        [-4., -4.]])

In [179]:
torch.mul(matrix1,matrix2)

tensor([[ 5., 12.],
        [21., 32.]])

In [180]:
torch.div(matrix1,matrix2)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

In [181]:
torch.matmul(matrix1,matrix2)

tensor([[19., 22.],
        [43., 50.]])

In [182]:
tensor1 =torch.tensor([[[1.,2.],[3.,4.]],[[5.,6],[7.,8]]])
print(tensor1)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [183]:
tensor2 =torch.tensor([[[9.,10.],[11.,12.]],[[13.,14],[15.,16]]])
print(tensor2)

tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


In [184]:
sum_tensor = tensor1 + tensor2
print(sum_tensor)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])


In [185]:
sub_tensor = tensor1 - tensor2
print(sub_tensor)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])


In [186]:
mul_tensor = tensor1 * tensor2
print(mul_tensor)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])


In [187]:
div_tensor = tensor1 / tensor2
print(div_tensor)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


In [188]:
torch.add(tensor1,tensor2)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])

In [189]:
torch.sub(tensor1,tensor2)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])

In [190]:
torch.mul(tensor1,tensor2)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])

In [191]:
torch.div(tensor1,tensor2)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])

In [192]:
torch.matmul(tensor1,tensor2)

tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])